version: '3'

services:
  mysqlserver:
    image: mysql/mysql-server
    container_name: mysqlserver
    env_file:
      - secrets.env
    volumes:
    - mysqldata:/var/lib/mysql
  api-services:
    build: .
    ports:
    - 8080:80
  sql-migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    tty: true


volumes:
  mysqldata:
