version: '3'

services:
  mysqlserver:
    image: mysql/mysql-server
    container_name: mysqlserver
    volumes:
    - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: WorkHourdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  api-services:
    build: .
    ports:
    - 8080:80

volumes:
  mysqldata:
