version: '3'

services:
  mysqlserver:
    image: mysql
    container_name: mysqlserver
    env_file:
      - .env
    volumes:
    - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  api-services:
    container_name: api-container
    build: .
    ports:
      - 8080:80

 # sql-migrations:
 #   container_name: sql-migrations
 #   build:
 #     context: .
 #     dockerfile: Dockerfile.migrations
 #   volumes:
 #     - ./:/App
 #   tty: true


volumes:
  mysqldata:

